// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "jni.h"
#include "dartjni.h"

thread_local JNIEnv *jniEnv;
JniContext *jni;

JniContext *(*context_getter)(void);
JNIEnv *(*env_getter)(void);

void setJniGetters(JniContext *(*cg)(void),
        JNIEnv *(*eg)(void)) {
    context_getter = cg;
    env_getter = eg;
}

// ch.masus.gni_location.JNILocation
jclass _c_JNILocation = NULL;

jmethodID _m_JNILocation__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult JNILocation__new0() {
    load_env();
        load_class_global_ref(&_c_JNILocation, "ch/masus/gni_location/JNILocation");
    if (_c_JNILocation == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_JNILocation,
      &_m_JNILocation__new0, "<init>", "()V");
    if (_m_JNILocation__new0 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_JNILocation, _m_JNILocation__new0);
    return to_global_ref_result(_result);
}

jmethodID _m_JNILocation__helloWorld = NULL;
FFI_PLUGIN_EXPORT
JniResult JNILocation__helloWorld(jobject message) {
    load_env();
        load_class_global_ref(&_c_JNILocation, "ch/masus/gni_location/JNILocation");
    if (_c_JNILocation == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_JNILocation,
      &_m_JNILocation__helloWorld, "helloWorld", "(Ljava/lang/String;)Ljava/lang/String;");
    if (_m_JNILocation__helloWorld == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_JNILocation, _m_JNILocation__helloWorld, message);
    return to_global_ref_result(_result);
}

